version: "3"

services:
  db_network:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  api:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_network
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:postgres@db_network:5432/postgres"

  minio:
      restart: always
      image: minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: dkfsdfj123j2143jlkl
        MINIO_ROOT_PASSWORD: gergrthrth56456456
      command:  server --console-address ":9001" /export
      volumes:
        - /minio/data:/export
        - /minio/config:/root/.minio