"""phone_number

Revision ID: 681fc1f09151
Revises: b2ef74daeaf7
Create Date: 2023-02-06 15:17:13.021808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681fc1f09151'
down_revision = 'b2ef74daeaf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
